version: 0.2
env:
  variables:
    IMAGE_NAME: "project_one_development"
  parameter-store:
    docker_username: "/project_one_development/docker_username"
    docker_password: "/project_one_development/docker_password"
    subnet: "/project_one_development/subnet"
    security_group: "/project_one_development/security_group"

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo --- Logging in to Amazon ECR ---
      - $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})
      - echo --- Setting AWS environments ---
      - echo --- Docker Login ---
      - echo $docker_password | docker login --username $docker_username --password-stdin
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
      - URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_NAME}
      - docker pull $URI:latest || true
  build:
    commands:
      - echo --- Building container ---
      - docker build --cache-from $URI:latest -f ./docker/development/Dockerfile -t $IMAGE_NAME:latest .
      - docker tag $IMAGE_NAME:latest $URI:latest
  post_build:
    commands:
      - docker push $URI:latest
      - printf '{"Version":"1.0","ImageURI":"%s"}' $URI:latest > imageDetail.json

artifacts:
  files:
    - imageDetail.json
    - ecs/development/taskdef.json
    - ecs/development/appspec.yaml
